### ISSUE TITLE
How to take ENV variable to guardfile

### ISSUE THREAD

**Issue by dersar00** [guard/guard#895]
my `environment_variables.rb` file

```ruby
module EnvironmentVariablesExample
  class Application < Rails::Application
    config.before_configuration do
      env_file = Rails.root.join("config", 'environment_variables.yml').to_s

      if File.exists?(env_file)
        YAML.load_file(env_file)[Rails.env].each do |key, value|
          ENV[key.to_s] = value
        end
      end
    end
  end
end
```

my `environment_variables.yml` file

```yaml
development:
    MYSQL_USERNAME: username
    MYSQL_PASSWORD: password
```

In the guardfile when i try to work with some ENV variable like ENV['MYSQL_PASSWORD'] it's always return me nil.
How can I take this variable?
